.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2020 Pau Amma <pauamma@gundo.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 28, 2020
.Dt BSDISKS 8
.Os
.Sh NAME
.Nm bsdisks
.Nd "daemon implementing the UDisks2 service"
.Sh SYNOPSIS
.Nm
.Op Fl -no-debug
.Op Fl -syslog-output
.Sh DESCRIPTION
The UDisks2 service provides interfaces to enumerate
and perform operations on disks and storage devices
via the D-Bus API.
The
.Nm
command is an implementation of the UDisks2 service for
.Fx .
The daemon is usually started by D-Bus daemon using its auto-activation feature,
thus no rc script is required.
The following option is available:
.Bl -tag -width indent
.It Fl -no-debug
Suppress debugging output (that is, do not output anything) to standard output.
.It Fl -syslog-output
Copies all output to
.Xr syslog 3
regardless of the presence of
.Fl -no-debug
.El
.Sh FILES
.Bl -tag -width /var/run/devd.seqpacket.pipe -compact
.It Pa /usr/local/etc/bsdisks.conf
Configuration file for
.Nm
.It Pa /usr/local/etc/syslog.d/bsdisks-syslog.conf
.Nm
configuration file for
.Xr syslogd 8
.It Pa /usr/local/etc/newsyslog.conf.d/bsdisks-newsyslog.conf
.Nm
configuration file for
.Xr newsyslog 8
.It Pa /var/run/devd.seqpacket.pipe
Pipe to read device and media events from
.Xr devd 8
.El
.Sh EXIT STATUS
.Ex -std
.Sh COMPATIBILITY
The
.Nm
utility is expected to be compatible with the UDisks2 daemon.
.Sh SEE ALSO
.Xr bsdisks.conf 5 ,
.Lk https://www.freedesktop.org/wiki/Software/udisks/
.Sh HISTORY
This manual page was written for version 0.17 of the
.Nm
utility.
.Sh AUTHORS
.An Gleb Popov Aq Mt arrowd@freebsd.org
wrote the
.Nm
utility, and
.An Pau Amma Aq Mt pauamma@gundo.com
wrote this manual page.
