/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a manager manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "manageradaptor.h"
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QMetaObject>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ObjectManagerAdaptor
 */

ObjectManagerAdaptor::ObjectManagerAdaptor(QObject* parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ObjectManagerAdaptor::~ObjectManagerAdaptor()
{
    // destructor
}

DBUSManagerStruct ObjectManagerAdaptor::GetManagedObjects()
{
    // handle method call org.freedesktop.DBus.ObjectManager.GetManagedObjects
    DBUSManagerStruct object_paths_interfaces_and_properties;
    QMetaObject::invokeMethod(parent(), "GetManagedObjects", Q_RETURN_ARG(DBUSManagerStruct, object_paths_interfaces_and_properties));
    return object_paths_interfaces_and_properties;
}
